export default [
  {
    id: 213,
    country: 'Afghanistan',
    country_abbr: 'AF',
    code: '+93',
    logo: '',
    name: '阿富汗',
  },
  {
    id: 210,
    country: 'Albania',
    country_abbr: 'AL',
    code: '+355',
    logo: '',
    name: '阿尔巴尼亚',
  },
  {
    id: 122,
    country: 'Algeria',
    country_abbr: 'DZ',
    code: '+213',
    logo: '',
    name: '阿尔及利亚',
  },
  {
    id: 206,
    country: 'American Samoa',
    country_abbr: 'AS',
    code: '+1684',
    logo: '',
    name: '美属萨摩亚',
  },
  {
    id: 215,
    country: 'Andorra',
    country_abbr: 'AD',
    code: '+376',
    logo: '',
    name: '安道尔',
  },
  {
    id: 208,
    country: 'Angola',
    country_abbr: 'AO',
    code: '+244',
    logo: '',
    name: '安哥拉',
  },
  {
    id: 211,
    country: 'Anguilla',
    country_abbr: 'AI',
    code: '+1264',
    logo: '',
    name: '安圭拉',
  },
  {
    id: 212,
    country: 'Antigua and Barbuda',
    country_abbr: 'AG',
    code: '+1268',
    logo: '',
    name: '安提瓜 和巴布达',
  },
  {
    id: 207,
    country: 'Argentina',
    country_abbr: 'AR',
    code: '+54',
    logo: '',
    name: '阿根廷',
  },
  {
    id: 209,
    country: 'Armenia',
    country_abbr: 'AM',
    code: '+374',
    logo: '',
    name: '亚美尼亚',
  },
  {
    id: 202,
    country: 'Aruba',
    country_abbr: 'AW',
    code: '+297',
    logo: '',
    name: '阿鲁巴',
  },
  {
    id: 203,
    country: 'Australia',
    country_abbr: 'AU',
    code: '+61',
    logo: '',
    name: '澳大利亚',
  },
  {
    id: 204,
    country: 'Austria',
    country_abbr: 'AT',
    code: '+43',
    logo: '',
    name: '奥地利',
  },
  {
    id: 201,
    country: 'Azerbaijan',
    country_abbr: 'AZ',
    code: '+994',
    logo: '',
    name: '阿塞拜疆',
  },
  {
    id: 179,
    country: 'Bahamas',
    country_abbr: 'BS',
    code: '+1242',
    logo: '',
    name: '巴哈马',
  },
  {
    id: 190,
    country: 'Bahrain',
    country_abbr: 'BH',
    code: '+973',
    logo: '',
    name: '巴林',
  },
  {
    id: 196,
    country: 'Bangladesh',
    country_abbr: 'BD',
    code: '+880',
    logo: '',
    name: '孟加拉国',
  },
  {
    id: 198,
    country: 'Barbados',
    country_abbr: 'BB',
    code: '+1246',
    logo: '',
    name: '巴巴多斯',
  },
  {
    id: 172,
    country: 'Belarus',
    country_abbr: 'BY',
    code: '+375',
    logo: '',
    name: '白俄罗斯',
  },
  {
    id: 195,
    country: 'Belgium',
    country_abbr: 'BE',
    code: '+32',
    logo: '',
    name: '比利时',
  },
  {
    id: 171,
    country: 'Belize',
    country_abbr: 'BZ',
    code: '+501',
    logo: '',
    name: '伯利兹',
  },
  {
    id: 188,
    country: 'Benin',
    country_abbr: 'BJ',
    code: '+229',
    logo: '',
    name: '贝宁',
  },
  {
    id: 187,
    country: 'Bermuda',
    country_abbr: 'BM',
    code: '+1441',
    logo: '',
    name: '百慕大群岛',
  },
  {
    id: 177,
    country: 'Bhutan',
    country_abbr: 'BT',
    code: '+975',
    logo: '',
    name: '不丹',
  },
  {
    id: 185,
    country: 'Bolivia',
    country_abbr: 'BO',
    code: '+591',
    logo: '',
    name: '玻利维亚',
  },
  {
    id: 183,
    country: 'Bonaire, Sint Eustatius and Saba',
    country_abbr: 'BQ',
    code: '+599',
    logo: '',
    name: '博内尔岛，圣尤斯特歇斯和萨巴',
  },
  {
    id: 199,
    country: 'Bosnia and Herzegovina',
    country_abbr: 'BA',
    code: '+387',
    logo: '',
    name: '波斯尼亚和黑塞哥维那',
  },
  {
    id: 174,
    country: 'Botswana',
    country_abbr: 'BW',
    code: '+267',
    logo: '',
    name: '博茨瓦纳',
  },
  {
    id: 180,
    country: 'Brazil',
    country_abbr: 'BR',
    code: '+55',
    logo: '',
    name: '巴西',
  },
  {
    id: 186,
    country: 'Brunei',
    country_abbr: 'BN',
    code: '+673',
    logo: '',
    name: '文莱',
  },
  {
    id: 191,
    country: 'Bulgaria',
    country_abbr: 'BG',
    code: '+359',
    logo: '',
    name: '保加利亚',
  },
  {
    id: 193,
    country: 'Burkina Faso',
    country_abbr: 'BF',
    code: '+226',
    logo: '',
    name: '布基纳法索',
  },
  {
    id: 189,
    country: 'Burundi',
    country_abbr: 'BI',
    code: '+257',
    logo: '',
    name: '布隆迪',
  },
  {
    country: 'China',
    country_abbr: 'cn',
    code: '+86',
    logo: '',
    name: '中国',
  },
  {
    id: 62,
    country: 'Cambodia',
    country_abbr: 'KH',
    code: '+855',
    logo: '',
    name: '柬埔寨',
  },
  {
    id: 150,
    country: 'Cameroon',
    country_abbr: 'CM',
    code: '+237',
    logo: '',
    name: '喀麦隆',
  },
  {
    id: 165,
    country: 'Canada',
    country_abbr: 'CA',
    code: '+1',
    logo: '',
    name: '加拿大',
  },
  {
    id: 144,
    country: 'Cape Verde',
    country_abbr: 'CV',
    code: '+238',
    logo: '',
    name: '开普',
  },
  {
    id: 56,
    country: 'Cayman Islands',
    country_abbr: 'KY',
    code: '+1345',
    logo: '',
    name: '开曼群岛',
  },
  {
    id: 160,
    country: 'Central African Republic',
    country_abbr: 'CF',
    code: '+236',
    logo: '',
    name: '中非共和国',
  },
  {
    id: 146,
    country: 'Chad',
    country_abbr: 'TD',
    code: '+235',
    logo: '',
    name: '乍得',
  },
  {
    id: 151,
    country: 'Chile',
    country_abbr: 'CL',
    code: '+56',
    logo: '',
    name: '智利',
  },
  {
    id: 149,
    country: 'Colombia',
    country_abbr: 'CO',
    code: '+57',
    logo: '',
    name: '哥伦比亚',
  },
  {
    id: 60,
    country: 'Comoros',
    country_abbr: 'KM',
    code: '+269',
    logo: '',
    name: '科摩罗',
  },
  {
    id: 152,
    country: 'Cook Islands',
    country_abbr: 'CK',
    code: '+682',
    logo: '',
    name: '库克群岛',
  },
  {
    id: 147,
    country: 'Costa Rica',
    country_abbr: 'CR',
    code: '+506',
    logo: '',
    name: '哥斯达黎加',
  },
  {
    id: 83,
    country: 'Croatia',
    country_abbr: 'HR',
    code: '+385',
    logo: '',
    name: '克罗地亚',
  },
  {
    id: 145,
    country: 'Cuba',
    country_abbr: 'CU',
    code: '+53',
    logo: '',
    name: '古巴',
  },
  {
    id: 142,
    country: 'Curacao',
    country_abbr: 'CW',
    code: '+599',
    logo: '',
    name: '库拉索',
  },
  {
    id: 140,
    country: 'Cyprus',
    country_abbr: 'CY',
    code: '+357',
    logo: '',
    name: '塞浦路斯',
  },
  {
    id: 138,
    country: 'Czech Republic',
    country_abbr: 'CZ',
    code: '+420',
    logo: '',
    name: '捷克',
  },
  {
    id: 161,
    country: 'Democratic Republic of the Congo',
    country_abbr: 'CD',
    code: '+243',
    logo: '',
    name: '刚果民主共和国',
  },
  {
    id: 127,
    country: 'Denmark',
    country_abbr: 'DK',
    code: '+45',
    logo: '',
    name: '丹麦',
  },
  {
    id: 129,
    country: 'Djibouti',
    country_abbr: 'DJ',
    code: '+253',
    logo: '',
    name: '吉布提',
  },
  {
    id: 126,
    country: 'Dominica',
    country_abbr: 'DM',
    code: '+1767',
    logo: '',
    name: '多米尼加',
  },
  {
    id: 137,
    country: 'East Timor',
    country_abbr: 'TL',
    code: '+670',
    logo: '',
    name: '东帝汶',
  },
  {
    id: 121,
    country: 'Ecuador',
    country_abbr: 'EC',
    code: '+593',
    logo: '',
    name: '厄瓜多尔',
  },
  {
    id: 118,
    country: 'Egypt',
    country_abbr: 'EG',
    code: '+20',
    logo: '',
    name: '埃及',
  },
  {
    id: 159,
    country: 'El Salvador',
    country_abbr: 'SV',
    code: '+503',
    logo: '',
    name: '萨尔瓦多',
  },
  {
    id: 91,
    country: 'Equatorial Guinea',
    country_abbr: 'GQ',
    code: '+240',
    logo: '',
    name: '赤道几内亚',
  },
  {
    id: 119,
    country: 'Estonia',
    country_abbr: 'EE',
    code: '+372',
    logo: '',
    name: '爱沙尼亚',
  },
  {
    id: 113,
    country: 'Ethiopia',
    country_abbr: 'ET',
    code: '+251',
    logo: '',
    name: '埃塞俄比亚',
  },
  {
    id: 105,
    country: 'Faroe Islands',
    country_abbr: 'FO',
    code: '+298',
    logo: '',
    name: '法罗群岛',
  },
  {
    id: 106,
    country: 'Fiji',
    country_abbr: 'FJ',
    code: '+679',
    logo: '',
    name: '斐济',
  },
  {
    id: 107,
    country: 'Finland',
    country_abbr: 'FI',
    code: '+358',
    logo: '',
    name: '芬兰',
  },
  {
    id: 104,
    country: 'France',
    country_abbr: 'FR',
    code: '+33',
    logo: '',
    name: '法国',
  },
  {
    id: 98,
    country: 'French Guiana',
    country_abbr: 'GF',
    code: '+594',
    logo: '',
    name: '法属圭亚那',
  },
  {
    id: 10,
    country: 'French Polynesia',
    country_abbr: 'PF',
    code: '+689',
    logo: '🇵🇫',
    name: '法属波利尼西亚',
  },
  {
    id: 103,
    country: 'Gabon',
    country_abbr: 'GA',
    code: '+241',
    logo: '',
    name: '加蓬',
  },
  {
    id: 94,
    country: 'Gambia',
    country_abbr: 'GM',
    code: '+220',
    logo: '',
    name: '冈比亚',
  },
  {
    id: 99,
    country: 'Georgia',
    country_abbr: 'GE',
    code: '+995',
    logo: '',
    name: '格鲁吉亚',
  },
  {
    id: 131,
    country: 'Germany',
    country_abbr: 'DE',
    code: '+49',
    logo: '',
    name: '德国',
  },
  {
    id: 97,
    country: 'Ghana',
    country_abbr: 'GH',
    code: '+233',
    logo: '',
    name: '加纳',
  },
  {
    id: 96,
    country: 'Gibraltar',
    country_abbr: 'GI',
    code: '+350',
    logo: '',
    name: '直布罗陀',
  },
  {
    id: 90,
    country: 'Greece',
    country_abbr: 'GR',
    code: '+30',
    logo: '',
    name: '希腊',
  },
  {
    id: 95,
    country: 'Greenland',
    country_abbr: 'GL',
    code: '+299',
    logo: '',
    name: '格陵兰岛',
  },
  {
    id: 100,
    country: 'Grenada',
    country_abbr: 'GD',
    code: '+1473',
    logo: '',
    name: '格林纳达',
  },
  {
    id: 92,
    country: 'Guadeloupe',
    country_abbr: 'GP',
    code: '+590',
    logo: '',
    name: '瓜德罗普岛',
  },
  {
    id: 88,
    country: 'Guam',
    country_abbr: 'GU',
    code: '+1671',
    logo: '',
    name: '关岛',
  },
  {
    id: 89,
    country: 'Guatemala',
    country_abbr: 'GT',
    code: '+502',
    logo: '',
    name: '瓜地马拉',
  },
  {
    id: 93,
    country: 'Guinea',
    country_abbr: 'GN',
    code: '+224',
    logo: '',
    name: '几内亚',
  },
  {
    id: 87,
    country: 'Guinea-Bissau',
    country_abbr: 'GW',
    code: '+245',
    logo: '',
    name: '几内亚比绍共和国',
  },
  {
    id: 86,
    country: 'Guyana',
    country_abbr: 'GY',
    code: '+592',
    logo: '',
    name: '圭亚那',
  },
  {
    id: 82,
    country: 'Haiti',
    country_abbr: 'HT',
    code: '+509',
    logo: '',
    name: '海地',
  },
  {
    id: 84,
    country: 'Honduras',
    country_abbr: 'HN',
    code: '+504',
    logo: '',
    name: '洪都拉斯',
  },
  {
    id: 85,
    country: 'Hong Kong(China)',
    country_abbr: 'HK',
    code: '+852',
    logo: '',
    name: '中国香港',
  },
  {
    id: 80,
    country: 'Hungary',
    country_abbr: 'HU',
    code: '+36',
    logo: '',
    name: '匈牙利',
  },
  {
    id: 71,
    country: 'Iceland',
    country_abbr: 'IS',
    code: '+354',
    logo: '',
    name: '冰岛',
  },
  {
    id: 75,
    country: 'India',
    country_abbr: 'IN',
    code: '+91',
    logo: '',
    name: '印度',
  },
  {
    id: 78,
    country: 'Indonesia',
    country_abbr: 'ID',
    code: '+62',
    logo: '',
    name: '印度尼西亚',
  },
  {
    id: 72,
    country: 'Iran',
    country_abbr: 'IR',
    code: '+98',
    logo: '',
    name: '伊朗',
  },
  {
    id: 73,
    country: 'Iraq',
    country_abbr: 'IQ',
    code: '+964',
    logo: '',
    name: '伊拉克',
  },
  {
    id: 77,
    country: 'Ireland',
    country_abbr: 'IE',
    code: '+353',
    logo: '',
    name: '爱尔兰',
  },
  {
    id: 76,
    country: 'Israel',
    country_abbr: 'IL',
    code: '+972',
    logo: '',
    name: '以色列',
  },
  {
    id: 70,
    country: 'Italy',
    country_abbr: 'IT',
    code: '+39',
    logo: '',
    name: '意大利',
  },
  {
    id: 155,
    country: 'Ivory Coast',
    country_abbr: 'CI',
    code: '+225',
    logo: '',
    name: '科特迪瓦',
  },
  {
    id: 224,
    country: 'Jamaica',
    country_abbr: 'JM',
    code: '+1658',
    logo: '',
    name: '牙买加',
  },
  {
    id: 67,
    country: 'Jamaica',
    country_abbr: 'JM',
    code: '+1876',
    logo: '',
    name: '牙买加',
  },
  {
    id: 65,
    country: 'Japan',
    country_abbr: 'JP',
    code: '+81',
    logo: '',
    name: '日本',
  },
  {
    id: 66,
    country: 'Jordan',
    country_abbr: 'JO',
    code: '+962',
    logo: '',
    name: '约旦',
  },
  {
    id: 55,
    country: 'Kazakhstan',
    country_abbr: 'KZ',
    code: '+7',
    logo: '',
    name: '哈萨克斯坦',
  },
  {
    id: 64,
    country: 'Kenya',
    country_abbr: 'KE',
    code: '+254',
    logo: '',
    name: '肯尼亚',
  },
  {
    id: 61,
    country: 'Kiribati',
    country_abbr: 'KI',
    code: '+686',
    logo: '',
    name: '基里巴斯',
  },
  {
    id: 57,
    country: 'Kuwait',
    country_abbr: 'KW',
    code: '+965',
    logo: '',
    name: '科威特',
  },
  {
    id: 63,
    country: 'Kyrgyzstan',
    country_abbr: 'KG',
    code: '+996',
    logo: '',
    name: '吉尔吉斯斯坦',
  },
  {
    id: 54,
    country: 'Laos',
    country_abbr: 'LA',
    code: '+856',
    logo: '',
    name: '老挝',
  },
  {
    id: 45,
    country: 'Latvia',
    country_abbr: 'LV',
    code: '+371',
    logo: '',
    name: '拉脱维亚',
  },
  {
    id: 53,
    country: 'Lebanon',
    country_abbr: 'LB',
    code: '+961',
    logo: '',
    name: '黎巴嫩',
  },
  {
    id: 48,
    country: 'Lesotho',
    country_abbr: 'LS',
    code: '+266',
    logo: '',
    name: '莱索托',
  },
  {
    id: 49,
    country: 'Liberia',
    country_abbr: 'LR',
    code: '+231',
    logo: '',
    name: '利比里亚',
  },
  {
    id: 44,
    country: 'Libya',
    country_abbr: 'LY',
    code: '+218',
    logo: '',
    name: '利比亚',
  },
  {
    id: 51,
    country: 'Liechtenstein',
    country_abbr: 'LI',
    code: '+423',
    logo: '',
    name: '列支敦士登',
  },
  {
    id: 47,
    country: 'Lithuania',
    country_abbr: 'LT',
    code: '+370',
    logo: '',
    name: '立陶宛',
  },
  {
    id: 46,
    country: 'Luxembourg',
    country_abbr: 'LU',
    code: '+352',
    logo: '',
    name: '卢森堡',
  },
  {
    id: 34,
    country: 'Macau(China)',
    country_abbr: 'MO',
    code: '+853',
    logo: '🇲🇴',
    name: '中国澳门',
  },
  {
    id: 38,
    country: 'Macedonia',
    country_abbr: 'MK',
    code: '+389',
    logo: '🇲🇰',
    name: '马其顿',
  },
  {
    id: 39,
    country: 'Madagascar',
    country_abbr: 'MG',
    code: '+261',
    logo: '',
    name: '马达加斯加',
  },
  {
    id: 26,
    country: 'Malawi',
    country_abbr: 'MW',
    code: '+265',
    logo: '🇲🇼',
    name: '马拉维',
  },
  {
    id: 24,
    country: 'Malaysia',
    country_abbr: 'MY',
    code: '+60',
    logo: '🇲🇾',
    name: '马来西亚',
  },
  {
    id: 27,
    country: 'Maldives',
    country_abbr: 'MV',
    code: '+960',
    logo: '🇲🇻',
    name: '马尔代夫',
  },
  {
    id: 37,
    country: 'Mali',
    country_abbr: 'ML',
    code: '+223',
    logo: '🇲🇱',
    name: '马里',
  },
  {
    id: 29,
    country: 'Malta',
    country_abbr: 'MT',
    code: '+356',
    logo: '🇲🇹',
    name: '马耳他',
  },
  {
    id: 33,
    country: 'Mariana Is',
    country_abbr: 'MP',
    code: '+1670',
    logo: '🇲🇵',
    name: '马里亚那群岛',
  },
  {
    id: 32,
    country: 'Martinique',
    country_abbr: 'MQ',
    code: '+596',
    logo: '🇲🇶',
    name: '马提尼克',
  },
  {
    id: 31,
    country: 'Mauritania',
    country_abbr: 'MR',
    code: '+222',
    logo: '🇲🇷',
    name: '毛里塔尼亚',
  },
  {
    id: 28,
    country: 'Mauritius',
    country_abbr: 'MU',
    code: '+230',
    logo: '🇲🇺',
    name: '毛里求斯',
  },
  {
    id: 79,
    country: 'Mayotte',
    country_abbr: 'YT',
    code: '+269',
    logo: '',
    name: '马约特',
  },
  {
    id: 25,
    country: 'Mexico',
    country_abbr: 'MX',
    code: '+52',
    logo: '🇲🇽',
    name: '墨西哥',
  },
  {
    id: 41,
    country: 'Moldova',
    country_abbr: 'MD',
    code: '+373',
    logo: '',
    name: '摩尔多瓦',
  },
  {
    id: 42,
    country: 'Monaco',
    country_abbr: 'MC',
    code: '+377',
    logo: '',
    name: '摩纳哥',
  },
  {
    id: 35,
    country: 'Mongolia',
    country_abbr: 'MN',
    code: '+976',
    logo: '🇲🇳',
    name: '蒙古',
  },
  {
    id: 40,
    country: 'Montenegro',
    country_abbr: 'ME',
    code: '+382',
    logo: '',
    name: '黑山',
  },
  {
    id: 30,
    country: 'Montserrat',
    country_abbr: 'MS',
    code: '+1664',
    logo: '🇲🇸',
    name: '蒙特塞拉特岛',
  },
  {
    id: 43,
    country: 'Morocco',
    country_abbr: 'MA',
    code: '+212',
    logo: '',
    name: '摩洛哥',
  },
  {
    id: 23,
    country: 'Mozambique',
    country_abbr: 'MZ',
    code: '+258',
    logo: '🇲🇿',
    name: '莫桑比克',
  },
  {
    id: 36,
    country: 'Myanmar',
    country_abbr: 'MM',
    code: '+95',
    logo: '🇲🇲',
    name: '缅甸',
  },
  {
    id: 22,
    country: 'Namibia',
    country_abbr: 'NA',
    code: '+264',
    logo: '🇳🇦',
    name: '纳米比亚',
  },
  {
    id: 15,
    country: 'Nepal',
    country_abbr: 'NP',
    code: '+977',
    logo: '🇳🇵',
    name: '尼泊尔',
  },
  {
    id: 17,
    country: 'Netherlands',
    country_abbr: 'NL',
    code: '+31',
    logo: '🇳🇱',
    name: '荷兰',
  },
  {
    id: 21,
    country: 'New Caledonia',
    country_abbr: 'NC',
    code: '+687',
    logo: '🇳🇨',
    name: '新喀里多尼亚',
  },
  {
    id: 14,
    country: 'New Zealand',
    country_abbr: 'NZ',
    code: '+64',
    logo: '🇳🇿',
    name: '新西兰',
  },
  {
    id: 18,
    country: 'Nicaragua',
    country_abbr: 'NI',
    code: '+505',
    logo: '🇳🇮',
    name: '尼加拉瓜',
  },
  {
    id: 20,
    country: 'Niger',
    country_abbr: 'NE',
    code: '+227',
    logo: '🇳🇪',
    name: '尼日尔',
  },
  {
    id: 19,
    country: 'Nigeria',
    country_abbr: 'NG',
    code: '+234',
    logo: '🇳🇬',
    name: '尼日利亚',
  },
  {
    id: 16,
    country: 'Norway',
    country_abbr: 'NO',
    code: '+47',
    logo: '🇳🇴',
    name: '挪威',
  },
  {
    id: 13,
    country: 'Oman',
    country_abbr: 'OM',
    code: '+968',
    logo: '🇴🇲',
    name: '阿曼',
  },
  {
    id: 7,
    country: 'Pakistan',
    country_abbr: 'PK',
    code: '+92',
    logo: '🇵🇰',
    name: '巴基斯坦',
  },
  {
    id: 219,
    country: 'Palau',
    country_abbr: 'PW',
    code: '+680',
    logo: '',
    name: '帕劳',
  },
  {
    id: 221,
    country: 'Palestinian Territory',
    country_abbr: 'PS',
    code: '+970',
    logo: '',
    name: '巴勒斯坦领土',
  },
  {
    id: 12,
    country: 'Panama',
    country_abbr: 'PA',
    code: '+507',
    logo: '🇵🇦',
    name: '巴拿马',
  },
  {
    id: 9,
    country: 'Papua New Guinea',
    country_abbr: 'PG',
    code: '+675',
    logo: '🇵🇬',
    name: '巴布亚新几内亚',
  },
  {
    id: 218,
    country: 'Paraguay',
    country_abbr: 'PY',
    code: '+595',
    logo: '',
    name: '巴拉圭',
  },
  {
    id: 11,
    country: 'Peru',
    country_abbr: 'PE',
    code: '+51',
    logo: '🇵🇪',
    name: '秘鲁',
  },
  {
    id: 8,
    country: 'Philippines',
    country_abbr: 'PH',
    code: '+63',
    logo: '🇵🇭',
    name: '菲律宾',
  },
  {
    id: 6,
    country: 'Poland',
    country_abbr: 'PL',
    code: '+48',
    logo: '🇵🇱',
    name: '波兰',
  },
  {
    id: 220,
    country: 'Portugal',
    country_abbr: 'PT',
    code: '+351',
    logo: '',
    name: '葡萄牙',
  },
  {
    id: 223,
    country: 'Puerto Rico',
    country_abbr: 'PR',
    code: '+1787',
    logo: '',
    name: '波多黎各',
  },
  {
    id: 217,
    country: 'Qatar',
    country_abbr: 'QA',
    code: '+974',
    logo: '',
    name: '卡塔尔',
  },
  {
    id: 158,
    country: 'Republic Of The Congo',
    country_abbr: 'CG',
    code: '+242',
    logo: '',
    name: '刚果共和国',
  },
  {
    id: 205,
    country: 'Réunion Island',
    country_abbr: 'RE',
    code: '+262',
    logo: '',
    name: '留尼汪',
  },
  {
    id: 200,
    country: 'Romania',
    country_abbr: 'RO',
    code: '+40',
    logo: '',
    name: '罗马尼亚',
  },
  {
    id: 194,
    country: 'Russia',
    country_abbr: 'RU',
    code: '+7',
    logo: '',
    name: '俄罗斯',
  },
  {
    id: 192,
    country: 'Rwanda',
    country_abbr: 'RW',
    code: '+250',
    logo: '',
    name: '卢旺达',
  },
  {
    id: 59,
    country: 'Saint Kitts and Nevis',
    country_abbr: 'KN',
    code: '+1869',
    logo: '',
    name: '圣基茨和尼维斯',
  },
  {
    id: 52,
    country: 'Saint Lucia',
    country_abbr: 'LC',
    code: '+1758',
    logo: '',
    name: '圣露西亚',
  },
  {
    id: 5,
    created_at: '2022-04-20T02:44:38.085848Z',
    updated_at: '2022-04-20T02:44:38.085848Z',
    country: 'Saint Pierre and Miquelon',
    country_abbr: 'PM',
    code: '+508',
    logo: '🇫🇷',
    name: '圣皮埃尔和密克隆',
  },
  {
    id: 115,
    country: 'Saint Vincent and The Grenadines',
    country_abbr: 'VC',
    code: '+1784',
    logo: '',
    name: '圣文森特和格林纳丁斯',
  },
  {
    id: 101,
    country: 'Samoa',
    country_abbr: 'WS',
    code: '+685',
    logo: '',
    name: '萨摩亚',
  },
  {
    id: 168,
    country: 'San Marino',
    country_abbr: 'SM',
    code: '+378',
    logo: '',
    name: '圣马力诺',
  },
  {
    id: 162,
    country: 'Sao Tome and Principe',
    country_abbr: 'ST',
    code: '+239',
    logo: '',
    name: '圣多美和普林西比',
  },
  {
    id: 184,
    country: 'Saudi Arabia',
    country_abbr: 'SA',
    code: '+966',
    logo: '',
    name: '沙特阿拉伯',
  },
  {
    id: 167,
    country: 'Senegal',
    country_abbr: 'SN',
    code: '+221',
    logo: '',
    name: '塞内加尔',
  },
  {
    id: 197,
    country: 'Serbia',
    country_abbr: 'RS',
    code: '+381',
    logo: '',
    name: '塞尔维亚',
  },
  {
    id: 181,
    country: 'Seychelles',
    country_abbr: 'SC',
    code: '+248',
    logo: '',
    name: '塞舌尔',
  },
  {
    id: 169,
    country: 'Sierra Leone',
    country_abbr: 'SL',
    code: '+232',
    logo: '',
    name: '塞拉利昂',
  },
  {
    id: 175,
    country: 'Singapore',
    country_abbr: 'SG',
    code: '+65',
    logo: '',
    name: '新加坡',
  },
  {
    id: 157,
    country: 'Sint Maarten (Dutch Part)',
    country_abbr: 'SX',
    code: '+1721',
    logo: '',
    name: '圣马丁岛（荷兰部分）',
  },
  {
    id: 170,
    country: 'Slovakia',
    country_abbr: 'SK',
    code: '+421',
    logo: '',
    name: '斯洛伐克',
  },
  {
    id: 173,
    country: 'Slovenia',
    country_abbr: 'SI',
    code: '+386',
    logo: '',
    name: '斯洛文尼亚',
  },
  {
    id: 182,
    country: 'Solomon Islands',
    country_abbr: 'SB',
    code: '+677',
    logo: '',
    name: '所罗门群岛',
  },
  {
    id: 166,
    country: 'Somalia',
    country_abbr: 'SO',
    code: '+252',
    logo: '',
    name: '索马里',
  },
  {
    id: 74,
    country: 'South Africa',
    country_abbr: 'ZA',
    code: '+27',
    logo: '',
    name: '南非',
  },
  {
    id: 58,
    country: 'South Korea',
    country_abbr: 'KR',
    code: '+82',
    logo: '',
    name: '韩国',
  },
  {
    id: 163,
    country: 'South Sudan',
    country_abbr: 'SS',
    code: '+211',
    logo: '',
    name: '南苏丹',
  },
  {
    id: 114,
    country: 'Spain',
    country_abbr: 'ES',
    code: '+34',
    logo: '',
    name: '西班牙',
  },
  {
    id: 50,
    country: 'Sri Lanka',
    country_abbr: 'LK',
    code: '+94',
    logo: '',
    name: '斯里兰卡',
  },
  {
    id: 178,
    country: 'Sudan',
    country_abbr: 'SD',
    code: '+249',
    logo: '',
    name: '苏丹',
  },
  {
    id: 164,
    country: 'Suriname',
    country_abbr: 'SR',
    code: '+597',
    logo: '',
    name: '苏里南',
  },
  {
    id: 153,
    country: 'Swaziland',
    country_abbr: 'SZ',
    code: '+268',
    logo: '',
    name: '斯威士兰',
  },
  {
    id: 176,
    country: 'Sweden',
    country_abbr: 'SE',
    code: '+46',
    logo: '',
    name: '瑞典',
  },
  {
    id: 156,
    country: 'Switzerland',
    country_abbr: 'CH',
    code: '+41',
    logo: '',
    name: '瑞士',
  },
  {
    id: 154,
    country: 'Syria',
    country_abbr: 'SY',
    code: '+963',
    logo: '',
    name: '叙利亚',
  },
  {
    id: 130,
    country: 'Taiwan(China)',
    country_abbr: 'TW',
    code: '+886',
    logo: '',
    name: '中国台湾',
  },
  {
    id: 139,
    country: 'Tajikistan',
    country_abbr: 'TJ',
    code: '+992',
    logo: '',
    name: '塔吉克斯坦',
  },
  {
    id: 128,
    country: 'Tanzania',
    country_abbr: 'TZ',
    code: '+255',
    logo: '',
    name: '坦桑尼亚',
  },
  {
    id: 141,
    country: 'Thailand',
    country_abbr: 'TH',
    code: '+66',
    logo: '',
    name: '泰国',
  },
  {
    id: 143,
    country: 'Togo',
    country_abbr: 'TG',
    code: '+228',
    logo: '',
    name: '多哥',
  },
  {
    id: 134,
    country: 'Tonga',
    country_abbr: 'TO',
    code: '+676',
    logo: '',
    name: '汤加',
  },
  {
    id: 132,
    country: 'Trinidad and Tobago',
    country_abbr: 'TT',
    code: '+1868',
    logo: '',
    name: '特立尼达和多巴哥',
  },
  {
    id: 135,
    country: 'Tunisia',
    country_abbr: 'TN',
    code: '+216',
    logo: '',
    name: '突尼斯',
  },
  {
    id: 133,
    country: 'Turkey',
    country_abbr: 'TR',
    code: '+90',
    logo: '',
    name: '土耳其',
  },
  {
    id: 136,
    country: 'Turkmenistan',
    country_abbr: 'TM',
    code: '+993',
    logo: '',
    name: '土库曼斯坦',
  },
  {
    id: 148,
    country: 'Turks and Caicos Islands',
    country_abbr: 'TC',
    code: '+1649',
    logo: '',
    name: '特克斯和凯科斯群岛',
  },
  {
    id: 123,
    country: 'Uganda',
    country_abbr: 'UG',
    code: '+256',
    logo: '',
    name: '乌干达',
  },
  {
    id: 124,
    country: 'Ukraine',
    country_abbr: 'UA',
    code: '+380',
    logo: '',
    name: '乌克兰',
  },
  {
    id: 214,
    country: 'United Arab Emirates',
    country_abbr: 'AE',
    code: '+971',
    logo: '',
    name: '阿拉伯联合酋长国',
  },
  {
    id: 102,
    country: 'United Kingdom',
    country_abbr: 'GB',
    code: '+44',
    logo: '',
    name: '英国',
  },
  {
    id: 120,
    country: 'United States',
    country_abbr: 'US',
    code: '+1',
    logo: '',
    name: '美国',
  },
  {
    id: 117,
    country: 'Uruguay',
    country_abbr: 'UY',
    code: '+598',
    logo: '',
    name: '乌拉圭',
  },
  {
    id: 116,
    country: 'Uzbekistan',
    country_abbr: 'UZ',
    code: '+998',
    logo: '',
    name: '乌兹别克斯坦',
  },
  {
    id: 108,
    country: 'Vanuatu',
    country_abbr: 'VU',
    code: '+678',
    logo: '',
    name: '瓦努阿图',
  },
  {
    id: 112,
    country: 'Venezuela',
    country_abbr: 'VE',
    code: '+58',
    logo: '',
    name: '委内瑞拉',
  },
  {
    id: 109,
    country: 'Vietnam',
    country_abbr: 'VN',
    code: '+84',
    logo: '',
    name: '越南',
  },
  {
    id: 111,
    country: 'Virgin Islands, British',
    country_abbr: 'VG',
    code: '+1340',
    logo: '',
    name: '英属处女群岛',
  },
  {
    id: 110,
    country: 'Virgin Islands, US',
    country_abbr: 'VI',
    code: '+1284',
    logo: '',
    name: '美属维尔京群岛',
  },
  {
    id: 81,
    country: 'Yemen',
    country_abbr: 'YE',
    code: '+967',
    logo: '',
    name: '也门',
  },
  {
    id: 69,
    country: 'Zambia',
    country_abbr: 'ZM',
    code: '+260',
    logo: '',
    name: '赞比亚',
  },
  {
    id: 68,
    country: 'Zimbabwe',
    country_abbr: 'ZW',
    code: '+263',
    logo: '',
    name: '津巴布韦',
  },
];
